### ISSUE TITLE
Why do you create hxE2?

### ISSUE THREAD

**Issue by Partysun** [PDeveloper/hxE2#1]
What is the new sauce of next hx entity framework and why do you decide to create it?

**Comment by PDeveloper** [comment]
I sum up several things and issues I had with hxE here:
http://psvilans.wrongbananas.net/hxe2-entity-systems/

If you have any more questions about specific things, please do ask, and I'll try to explain as best I can! In short, I felt the design of hxE was too limiting, and didn't offer much opportunity to expand it. hxE2 limits its responsibility much more.

TL;DR
The most obvious difference is the addition of Views as a means of accessing components, rather than component filters being a part of Systems.

**Comment by PDeveloper** [comment]
I want to note:
hxE2 does NOT deprecate hxE, it just offers a different way of working with an ECS! : )

**Comment by Partysun** [comment]
Yes, It seems like another behavior of ecs. Thank you. Is view like node in ash?

**Comment by PDeveloper** [comment]
I have not used Ash, and so I can't say! Also note, that for now, if you're having trouble with performance, hxE is currently faster I think.
